### ISSUE TITLE
Error clonar dependecias en archivo pip.txt

### ISSUE THREAD

**Issue by outis10** [Tecnativa/doodba-scaffolding#30]
Al ejecutar el comando docker-compose build --pull
me marca un error al clonar  lo siguiente
`` Collecting` git+https://github.com/OCA/openupgradelib.git@master (from -r /opt/odoo/custom/dependencies/pip.txt (line 1))``
revisando el archivo  pip txt
veo que tiene dos palabras: 

> unicodecsv y unidecode

pip.txt
> git+https://github.com/OCA/openupgradelib.git@master
unicodecsv
unidecode

como no se que hacen se las quite al archivo y corri de nuevo el comando y se ejecuto correctamente.

Estoy trabajando en windos 10 con el wsl en ubuntu.

Saludos

**Comment by pedrobaeza** [comment]
Si no indicas cuál es el error que te sale al clonar, es difícil poder ayudarte.

**Comment by outis10** [comment]
al ejecutar el commando:

> docker-compose -f setup-devel.yaml run --rm odoo

arroja el siguiente log:

```
---> Running in 8fcd6e89d306
doodba WARNING: Not aggregating code repositories
doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/apt_build.txt
doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/apt.txt
doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/gem.txt
doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/npm.txt
doodba INFO: Executing: ['pip', 'install', '--no-cache-dir', '-r', '/opt/odoo/custom/dependencies/pip.txt']

`Collecting`` git+https://github.com/OCA/openupgradelib.git@master (from -r /opt/odoo/custom/dependencies/pip.txt (line `1))`
  Cloning https://github.com/OCA/openupgradelib.git (to revision master) to `/tmp/pip-req-build-f5o34_mp`
Collecting unicodecsv (from -r /opt/odoo/custom/dependencies/pip.txt (line 2))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError(0, 'Error'))': `/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz`
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError(0, 'Error'))': `/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz`

  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError(0, 'Error'))': /packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError(0, 'Error'))': /packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError(0, 'Error'))': /packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz (Caused by ProtocolError('Connection aborted.', OSError(0, 'Error')))

Traceback (most recent call last):
  File "/opt/odoo/common/build.d/200-dependencies", line 23, in <module>
    install(name, req_file)
  File "/usr/local/lib/python3.5/site-packages/doodbalib/installer.py", line 121, in install
    return INSTALLERS[installer](file_path).install()
  File "/usr/local/lib/python3.5/site-packages/doodbalib/installer.py", line 31, in install
    self._install_command + self._requirements)
  File "/usr/local/lib/python3.5/site-packages/doodbalib/installer.py", line 20, in _run_command
    return check_call(command, shell=isinstance(command, str))
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '--no-cache-dir', '-r', '/opt/odoo/custom/dependencies/pip.txt']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 32, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/common/build.d/200-dependencies' returned non-zero exit status 1
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1
```

**Comment by pedrobaeza** [comment]
Eso es problemas de conexión a Internet.

**Comment by yajo** [comment]
Exacto, nada más que hacer aquí por nuestra parte. :wink:
